const seed={people:[{id:'hunter',name:'Hunter',colour:'#e16b55',target:300},{id:'amelia',name:'Amelia',colour:'#7867a8',target:300},{id:'david',name:'David',colour:'#176b5b',target:300},{id:'lydia',name:'Lydia',colour:'#c78d31',target:300}],tasks:[
{id:'dress',name:'Get dressed',person:'hunter',category:'Ready for the day',points:0,active:true},{id:'breakfast',name:'Eat breakfast',person:'hunter',category:'Ready for the day',points:0,active:true},{id:'teeth',name:'Brush teeth',person:'hunter',category:'Ready for the day',points:0,active:true},{id:'room',name:'Quick bedroom tidy',person:'hunter',category:'Ready for the day',points:2,active:true},{id:'spell',name:'Spelling test',person:'hunter',category:'Schoolwork',points:5,active:true},{id:'read-h',name:'Read together or independently',person:'hunter',category:'Schoolwork',points:5,active:true},{id:'maths-h',name:'Maths activity',person:'hunter',category:'Schoolwork',points:5,active:true},{id:'science-h',name:'Choose: science, geography or geology',person:'hunter',category:'Schoolwork',points:5,active:true},
{id:'dog',name:'Walk the dog',person:'amelia',category:'Essentials',points:0,active:true},{id:'dishwasher',name:'Load the dishwasher',person:'amelia',category:'Essentials',points:0,active:true},{id:'constructive-a',name:'Choose something constructive',person:'amelia',category:'Today',points:5,active:true},{id:'gcse-a',name:'Complete a chosen GCSE task',person:'amelia',category:'Earn more',points:10,active:true},
{id:'french-d',name:'French learning',person:'david',category:'Personal goals',points:5,active:true},{id:'exercise-d',name:'Run or exercise',person:'david',category:'Personal goals',points:5,active:true},{id:'project-d',name:'Useful job or personal project',person:'david',category:'Personal goals',points:10,active:true},
{id:'phd-l',name:'PhD progress',person:'lydia',category:'Personal goals',points:10,active:true},{id:'yoga-l',name:'Yoga, walk or other exercise',person:'lydia',category:'Personal goals',points:5,active:true},{id:'garden-l',name:'Gardening or useful job',person:'lydia',category:'Personal goals',points:5,active:true}],outings:[
{id:'whitby',name:'Whitby',location:'england',weather:'either',time:'full',cost:'paid',repeat:'once',active:true},{id:'vindolanda',name:'Vindolanda or another Roman site',location:'england',weather:'either',time:'full',cost:'paid',repeat:'once',active:true},{id:'swim',name:'Swimming',location:'england',weather:'either',time:'half',cost:'paid',repeat:'often',active:true},{id:'park',name:'Hexham Park',location:'england',weather:'dry',time:'short',cost:'free',repeat:'often',active:true},{id:'trampoline',name:'Trampoline park',location:'england',weather:'wet',time:'half',cost:'paid',repeat:'occasional',active:true},{id:'museum',name:'Great North Museum',location:'england',weather:'wet',time:'half',cost:'free',repeat:'once',active:true},{id:'bike',name:'Bike ride or pump track',location:'england',weather:'dry',time:'short',cost:'free',repeat:'often',active:true},
{id:'beach-d',name:'Dieppe beach and seafront',location:'france',weather:'dry',time:'half',cost:'free',repeat:'often',active:true},{id:'harbour-d',name:'Explore Dieppe harbour',location:'france',weather:'either',time:'short',cost:'free',repeat:'often',active:true},{id:'estran',name:'ESTRAN Cité de la Mer',location:'france',weather:'wet',time:'half',cost:'paid',repeat:'occasional',active:true},{id:'chateau-d',name:'Château-Musée de Dieppe',location:'france',weather:'wet',time:'half',cost:'paid',repeat:'once',active:true},{id:'pirate-d',name:'L’Îlot Pirate',location:'france',weather:'wet',time:'half',cost:'paid',repeat:'occasional',active:true},{id:'arb',name:'Arb’Aventure',location:'france',weather:'dry',time:'half',cost:'paid',repeat:'once',active:true},{id:'fossils',name:'Fossil or rock search',location:'france',weather:'dry',time:'short',cost:'free',repeat:'often',active:true},{id:'avenue',name:'Walk or cycle the Avenue Verte',location:'france',weather:'dry',time:'half',cost:'free',repeat:'often',active:true}],completions:[],memories:[],plans:{hunter:'Morning jobs, schoolwork, then see where the day takes us.',amelia:'Essentials, something constructive, then the day is yours.',david:'Family plans and one personal goal.',lydia:'PhD progress if useful; everything else is optional.'}};
let data=JSON.parse(localStorage.getItem('ourDaysData')||'null')||structuredClone(seed),currentPerson='hunter',manageType='tasks';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],save=()=>localStorage.setItem('ourDaysData',JSON.stringify(data));
function todayKey(){return new Date().toISOString().slice(0,10)}
function completed(taskId){return data.completions.some(x=>x.taskId===taskId&&x.date===todayKey())}
function init(){ $('#todayDate').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long'}).format(new Date()); $('#personSelect').innerHTML=data.people.map(p=>`<option value="${p.id}">${p.name}</option>`).join(''); bind(); renderAll() }
function bind(){ $$('.bottom-nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page)); $('#settingsButton').onclick=()=>showPage('manage'); $('#personSelect').onchange=e=>{currentPerson=e.target.value;renderToday()}; $('#changePlan').onclick=()=>{$('#planInput').value=data.plans[currentPerson]||'';$('#planDialog').showModal()}; $('#savePlan').onclick=()=>{data.plans[currentPerson]=$('#planInput').value;save();renderToday()}; $('#quickMemory').onclick=$('#addMemory').onclick=()=>$('#memoryDialog').showModal(); $('#saveMemory').onclick=addMemory; ['location','weather','time','cost'].forEach(x=>$(`#${x}Filter`).onchange=renderOutings); $('#spinButton').onclick=spin; $$('.manage-tabs button').forEach(b=>b.onclick=()=>{manageType=b.dataset.manage;$$('.manage-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderManage()}); $('#addRow').onclick=addRow; $('#resetData').onclick=()=>{if(confirm('Reset all prototype changes and completions?')){data=structuredClone(seed);save();renderAll()}} }
function showPage(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));if(id==='manage')renderManage();window.scrollTo(0,0)}
function renderAll(){renderToday();renderOutings();renderProgress();renderMemories();renderManage()}
function renderToday(){const tasks=data.tasks.filter(t=>t.person===currentPerson&&t.active),groups=Object.groupBy(tasks,t=>t.category);$('#planText').textContent=data.plans[currentPerson]||'';$('#taskGroups').innerHTML=Object.entries(groups).map(([g,ts])=>`<section class="task-section"><h3>${g}</h3><div class="task-grid">${ts.map(t=>`<label class="task ${completed(t.id)?'done':''}"><input type="checkbox" data-task="${t.id}" ${completed(t.id)?'checked':''}><span>${t.name}</span>${t.points?`<span class="points">+${t.points}</span>`:''}</label>`).join('')}</div></section>`).join('');$$('[data-task]').forEach(c=>c.onchange=()=>toggleTask(c.dataset.task,c.checked))}
function toggleTask(id,on){data.completions=data.completions.filter(x=>!(x.taskId===id&&x.date===todayKey()));if(on){const t=data.tasks.find(x=>x.id===id);data.completions.push({taskId:id,person:t.person,date:todayKey(),points:t.points})}save();renderToday();renderProgress()}
function eligible(o){const loc=$('#locationFilter').value,w=$('#weatherFilter').value,t=$('#timeFilter').value,c=$('#costFilter').value;return o.active&&o.location===loc&&(w==='either'||o.weather==='either'||o.weather===w)&&(t==='any'||o.time===t)&&(c==='any'||o.cost===c)}
function renderOutings(){const list=data.outings.filter(o=>o.location===$('#locationFilter').value),n=list.filter(eligible).length;$('#eligibleCount').textContent=`${n} available`;$('#outingList').innerHTML=list.map(o=>`<div class="outing ${eligible(o)?'':'ineligible'}"><div><strong>${o.name}</strong><p>${o.time} · ${o.weather} weather · ${o.cost}</p></div><span class="tag">${o.repeat}</span></div>`).join('')}
function spin(){const options=data.outings.filter(eligible);if(!options.length){$('#wheelLabel').textContent='No matches';return}const choice=options[Math.floor(Math.random()*options.length)],wheel=$('#wheel');wheel.classList.remove('spinning');void wheel.offsetWidth;wheel.classList.add('spinning');$('#wheelLabel').textContent='Spinning…';setTimeout(()=>{$('#wheelLabel').textContent=choice.name;wheel.classList.remove('spinning')},2200)}
function renderProgress(){const totals=Object.fromEntries(data.people.map(p=>[p.id,data.completions.filter(c=>c.person===p.id).reduce((s,c)=>s+c.points,0)]));$('#progressCards').innerHTML=data.people.map(p=>{const pts=totals[p.id],next=Math.ceil((pts+1)/100)*100||100,cash=Math.floor(pts/100)*5;return`<article class="progress-card"><div class="avatar" style="background:${p.colour}">${p.name[0]}</div><h3>${p.name}</h3><strong>${pts} points</strong><div class="progress-track"><div class="progress-fill" style="width:${pts%100}%"></div></div><p class="muted">${next-pts} to the next £5 · £${cash} unlocked</p></article>`}).join('')}
function addMemory(e){const title=$('#memoryTitle').value.trim();if(!title){e.preventDefault();return}const file=$('#memoryPhoto').files[0];data.memories.unshift({id:crypto.randomUUID(),title,text:$('#memoryText').value,date:todayKey(),photo:file?URL.createObjectURL(file):''});save();setTimeout(()=>{$('#memoryTitle').value='';$('#memoryText').value='';$('#memoryPhoto').value='';renderMemories()},0)}
function renderMemories(){const el=$('#memoryList');if(!data.memories.length){el.innerHTML='<div class="empty">Your Summer 2026 memories will appear here.<br>Add ordinary moments as well as big days out.</div>';return}el.innerHTML=data.memories.map(m=>`<article class="memory-card">${m.photo?`<img src="${m.photo}" alt="">`:''}<div class="memory-body"><p class="memory-date">${new Date(m.date+'T12:00').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</p><h3>${m.title}</h3><p>${m.text||''}</p></div></article>`).join('')}
function renderManage(){const items=data[manageType],isTask=manageType==='tasks';$('#manageTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Name</th>${isTask?'<th>Person</th><th>Category</th><th>Points</th>':'<th>Location</th><th>Weather</th><th>Time</th>'}<th>Active</th></tr></thead><tbody>${items.map((x,i)=>`<tr><td><input data-field="name" data-i="${i}" value="${x.name}"></td>${isTask?`<td><select data-field="person" data-i="${i}">${data.people.map(p=>`<option value="${p.id}" ${x.person===p.id?'selected':''}>${p.name}</option>`).join('')}</select></td><td><input data-field="category" data-i="${i}" value="${x.category}"></td><td><input type="number" data-field="points" data-i="${i}" value="${x.points}"></td>`:`<td><select data-field="location" data-i="${i}"><option value="england" ${x.location==='england'?'selected':''}>England</option><option value="france" ${x.location==='france'?'selected':''}>France</option></select></td><td><select data-field="weather" data-i="${i}"><option value="either">Either</option><option value="dry" ${x.weather==='dry'?'selected':''}>Dry</option><option value="wet" ${x.weather==='wet'?'selected':''}>Wet</option></select></td><td><select data-field="time" data-i="${i}"><option value="short">Short</option><option value="half" ${x.time==='half'?'selected':''}>Half-day</option><option value="full" ${x.time==='full'?'selected':''}>Full day</option></select></td>`}<td><input type="checkbox" data-field="active" data-i="${i}" ${x.active?'checked':''}></td></tr>`).join('')}</tbody></table></div>`;$$('#manageTable [data-field]').forEach(el=>el.onchange=()=>{const item=data[manageType][+el.dataset.i],f=el.dataset.field;item[f]=el.type==='checkbox'?el.checked:el.type==='number'?+el.value:el.value;save();renderAll()})}
function addRow(){if(manageType==='tasks')data.tasks.push({id:crypto.randomUUID(),name:'New task',person:'hunter',category:'Other',points:5,active:true});else data.outings.push({id:crypto.randomUUID(),name:'New outing',location:'england',weather:'either',time:'half',cost:'free',repeat:'often',active:true});save();renderManage()}
init();
